export  default {
    SEARCH_CITY_ACTION: 'FORECAST_SEARCH_CITY_ACTION',
    INIT_LOAD_CITIES_ACTION: "INIT_LOAD_CITIES_ACTION",  
    SEARCH_CITY_MUTATION: 'FORECAST_SEARCH_CITY_MUTATION',
    INIT_LOAD_CITIES_MUTATION: "INIT_LOAD_CITIES_MUTATION",
    ACTIVE_CITY_GETTER: 'FORECAST_ACTIVE_CITY_GETTER',
    LOADED_CITIES_GETTER: 'LOADED_CITIES_GETTER',
    GET_MOCK_GETTER: 'GET_MOCK_GETTER',
    CITIES_TO_SEARCH_GETTER: "CITIES_TO_SEARCH_GETTER"
}